### PR TITLE
Code cleaned up, pep8 and i18n!

### PR DESCRIPTION
**Pull request by m431m**
Hi,

I propose this pull-request:

* code was cleaned up based on pep8 (careful with indentation ;-)
* I added full i18n support and french translation
* and some minor improvements

Of course, I recommend to test it before merging first.

m431m

### CODE REVIEW

**Comment by espona** [comment]
Thanks for your contribution. There are so many changes I could hardly review everything, I have barely time for this project. I resolved conflicting changes and merged, I guess it works for you. I will test it as soon as I can. Best, L

**Comment by m431m** [comment]
You're welcome,
I have time for review the code. If I find bugs, I would correct them.
m431m

**Comment by espona** [comment]
I just fixed one issue at i18n/ckanext-restricted.pot. I have a problem with access request mails, they no longer display as before. All the mail is in one line without line breaks, can you review this? Many thanks

screen shot 2018-07-31 at 17 29 40

**Comment by m431m** [comment]
> I just fixed one issue at i18n/ckanext-restricted.pot

Bad copy-paste...

> I have a problem with access request mails, they no longer display as before. All the mail is in one line without line breaks, can you review this? Many thanks

Of course, I will fix it.

**Comment by espona** [comment]
Also, no mail is sent after dataset owner adds a new user to the "allowed users".  Does this work for you?

**Comment by m431m** [comment]
Ok, I'll check this tomorrow morning, correct mistakes and make a patch.

**Comment by espona** [comment]
I just fixed that with the mails sent when a new user is allowed, it was just a missing import. This mails also display without line breaks. Hopefully that is easy to fix too :)

**Comment by m431m** [comment]
Hi, I found what's wrong with e-mail. The Jinja i18n `{% trans %}` tag destroy all line break....
I will fix it today.

**Comment by espona** [comment]
Ok, I guess you need a {% trans %} per line. You can change the mail contents to make it more compact, so that less line breaks are needed, maybe that makes it simpler.

**Comment by m431m** [comment]
Yes absolutely.
I will keep the content without changing it.

**Comment by m431m** [comment]
Patch here: #8

**Pull request merged**
